# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: 
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'c88267eb-7f60-4620-bdac-44c5da10f56e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/sridharthangella/AzureRmPipeline-repo/tree/main/AzureRmPipeline-repo/CreateWebApp'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'